apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # There is no namespace.yaml because this is managed by terraform.
  - service.yaml
  - deployment.yaml
  - config-map.yaml
