apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          env:
            - name: INSTRUMENTATION_KEY
              value: "18be3b83-4ad5-4186-a7b6-f65dd1253a77"
            - name: FAVOURITE_CUISINE
              valueFrom:
                secretKeyRef:
                  name: favouritecuisine
                  key: favouritecuisine
