apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          env:
            - name: INSTRUMENTATION_KEY
              value: "$INSTRUMENTATION_KEY"
            - name: FAVOURITE_CUISINE
              valueFrom:
                secretKeyRef:
                  name: favourite-cuisine
                  key: favouritecuisine
