apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favouritecuisine
  namespace: hello-world
spec:
  encryptedData:
    favouritecuisine: AgBNeMQbyKWK0dm6P7eI1640aw8YHu39U1QDbgQtAozUMJhiEDtn4rX5SITeh8juJNiaoThrgjWdDVDOT4/vgUdflkxU2qskbNxEN8vvYRakPPu72ns/flLIKS6oXoVeG2uRvNpYi0qCOU26r3WcNflN4AIg8+65DllepmPEAKJIGaHagG+P07bLpCvo+TkR9az0yZcChho6ynJXard42+bxgPlINE9KmQ7zKjPkiUVRnYv5NNfwkxFto+LEfylBSKggOoByhJOcq5VMy81IMNTlCS1gj3P+Mb4fFUTMflHFiIQG56sSIJn1qPah6XuQUVrHzuXMCyDMRU8uSpTAKEm0ngZr3AD2+Q670/yRdsVNl8H9fJqZLT2GnoXR6x2EXCe3MOmwWm75Qp1Y2ANmBkNaNk1OsTkJjSujTIWQFxmpYOS7zg/L+d/zMoTRoZHAEpc8W4ks+eGAzHT0KDDFQnN8KQFf2nE1p3BjIBdVTBg4xeFK7i5KmGInmbk5IhPXrICzM7BID/nfNJAqyNhAY4OEgZCUxP6bKN6Cc7br2ikGky1C8CrKnTaiO5MjTOO1KrSAMVYPVjQjFBZUksVMgNdMFuxl1jZlpy0Nz5U0t1S/C9wSD9ZLvXAFckaU8TEGWBiJKkpMsSDXFYPsOonqxjqgJlnsaB6pJFlRugOM+SxY1QwAI0wHf1CrUtKai0ezB1T69DDaqT/A
  template:
    metadata:
      creationTimestamp: null
      name: favouritecuisine
      namespace: hello-world
