name: event-models-branch

on:
  pull_request:
    branches:
      - master
    paths:
      - event-models/**
      - .github/workflows/event-models-branch.yaml

jobs:
  updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Check if types are up-to-date
        working-directory: event-models
        run: |
          set -eu
          yarn
          yarn generate
          if [[ $(git diff --stat) != '' ]]; then
            echo "Git repository contains changes after running 'yarn generate'."
            echo "Did you update the schema.json but forgot to update the types?"
            exit 1
          fi
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test Rust types
        working-directory: event-models/rust
        run: cargo test
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test TypeScript types
        working-directory: event-models/typescript
        run: |
          set -eu
          yarn
          yarn test
