name: frontend-master

on:
  push:
    branches:
      - master
    paths:
      - frontend/**
      - .github/workflows/frontend-master.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - name: "Login to docker"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: "Build & Push image"
        run: |
          cd $GITHUB_WORKSPACE/futurenhs-platform/frontend
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${TAG}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${TAG}
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${TAG})"
          echo ::set-env name=TAG::$TAG
          echo ::set-env name=DIGEST::$DIGEST

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy manifests
        run: |
          set -eux
          $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/frontend
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/frontend/manifests/* $GITHUB_WORKSPACE/futurenhs-deployments/frontend

      - name: Update image tag and deploy

        run: |
          set -eux

          cd $HOME
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          cd $GITHUB_WORKSPACE/futurenhs-deployments/frontend/production

          $HOME/kustomize edit set image $DIGEST

          git config --local user.email "futurenhs-devs@red-badger.com"
          git config --local user.name "FutureNHS CI/CD"

          git add -A
          git diff-index --quiet HEAD || git commit -am "CI: Update production image for ${TAG}"

          declare -i n
          n=0
          until [ $n -ge 5 ]
          do
            git push && break
            n+=1
            git pull --rebase
          done

          if [ $n -ge 5 ]
          then
            echo "ran out of retries"
            exit 1
          fi 
