name: infrastructure-master

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure-master.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy manifests
        run: |
          set -eux
          $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/cert-manager
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/kubernetes/cert-manager/* $GITHUB_WORKSPACE/futurenhs-deployments/cert-manager
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/ingress
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/kubernetes/ingress/* $GITHUB_WORKSPACE/futurenhs-deployments/ingress
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/kratos
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/kubernetes/kratos/* $GITHUB_WORKSPACE/futurenhs-deployments/kratos

      - name: Deploy
        run: |
          set -eux
          cd $GITHUB_WORKSPACE/futurenhs-deployments

          git config --local user.email "futurenhs-devs@red-badger.com"
          git config --local user.name "FutureNHS CI/CD"

          git add -A
          git diff-index --quiet HEAD || git commit -am "CI: Update cert-manager and ingress"

          declare -i n
          n=0
          until [ $n -ge 5 ]
          do
            git push && break
            n+=1
            git pull --rebase
          done

          if [ $n -ge 5 ]
          then
            echo "ran out of retries"
            exit 1
          fi
