name: infrastructure-branch

on:
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure-branch.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0
      - name: Validate Terraform of dev environment
        working-directory: futurenhs-platform/infrastructure/environments/dev
        run: |
          set -euxo pipefail
          terraform init -backend=false
          terraform validate
      - name: Validate Terraform of shared dev environment
        working-directory: futurenhs-platform/infrastructure/environments/shared-dev
        run: |
          set -euxo pipefail
          terraform init -backend=false
          terraform validate
      - name: Validate Terraform of production environment
        working-directory: futurenhs-platform/infrastructure/environments/production
        run: |
          set -euxo pipefail
          terraform init -backend=false
          terraform validate
      - name: get commit message
        working-directory: futurenhs-platform
        run: |
          set -euxo pipefail
          git fetch origin HEAD --deepen=2
          echo ::set-env name=COMMIT_MESSAGE::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Checkout the correct Deployments repo branch
        working-directory: futurenhs-deployments
        run: |
          set -euxo pipefail
          git config --local user.email "futurenhs-devs@red-badger.com"
          git config --local user.name "FutureNHS CI/CD"
          if git fetch --unshallow origin pr-$GITHUB_HEAD_REF master ; then
            git checkout origin/pr-$GITHUB_HEAD_REF -b pr-$GITHUB_HEAD_REF
            git merge origin/master --strategy=recursive --strategy-option=ours
          else
            git checkout HEAD -b pr-$GITHUB_HEAD_REF
          fi
      - name: Copy manifests
        run: |
          set -euxo pipefail
          $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py
          # TODO: this is a lot of copy-paste, and duplicates the array that lives in create-dev-overlays.py
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/cert-manager
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/kubernetes/cert-manager/* $GITHUB_WORKSPACE/futurenhs-deployments/cert-manager
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/ingress
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/kubernetes/ingress/* $GITHUB_WORKSPACE/futurenhs-deployments/ingress
      - name: Deploy
        working-directory: futurenhs-deployments
        run: |
          set -euxo pipefail

          git add -A
          # TODO: can we make this commit message reflect the message at the tip of the platform repo?
          git diff-index --quiet HEAD || git commit -am "infrastructure-branch: $COMMIT_MESSAGE"

          declare -i n
          n=0
          until [ $n -ge 5 ]
          do
            git push origin "HEAD:pr-$GITHUB_HEAD_REF" && break
            n+=1
            git fetch origin pr-$GITHUB_HEAD_REF
            git merge origin/pr-$GITHUB_HEAD_REF --strategy=recursive --strategy-option=ours
          done

          if [ $n -ge 5 ]
          then
            echo "ran out of retries"
            exit 1
          fi
