name: infrastructure-branch

on:
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure-branch.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25
      - name: Check Terraform format
        run: terraform fmt -recursive -check
        working-directory: futurenhs-platform/infrastructure
      - name: Validate Terraform of dev environment
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: futurenhs-platform/infrastructure/environments/dev
      - name: Validate Terraform of production environment
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: futurenhs-platform/infrastructure/environments/production
      - name: Test dev overlay creation
        run: $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Checkout the correct Deployments repo branch
        working-directory: futurenhs-deployments
        run: |
          if git fetch origin pr-$GITHUB_HEAD_REF ; then
            git checkout origin/pr-$GITHUB_HEAD_REF -b pr-$GITHUB_HEAD_REF
          else
            git checkout HEAD -b pr-$GITHUB_HEAD_REF
          fi
          
      - name: Copy manifests
        run: |
          set -eux
          cd $GITHUB_WORKSPACE/futurenhs-deployments
          $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py
          # TODO: this is a lot of copy-paste, and duplicates the array that lives in create-dev-overlays.py
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/cert-manager
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/kubernetes/cert-manager/* $GITHUB_WORKSPACE/futurenhs-deployments/cert-manager
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/ingress
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/kubernetes/ingress/* $GITHUB_WORKSPACE/futurenhs-deployments/ingress

      - name: Deploy
        run: |
          set -eux
          cd $GITHUB_WORKSPACE/futurenhs-deployments

          git config --local user.email "futurenhs-devs@red-badger.com"
          git config --local user.name "FutureNHS CI/CD"

          git add -A
          # TODO: can we make this commit message reflect the message at the tip of the platform repo?
          git diff-index --quiet HEAD || git commit -am "CI: Update cert-manager and ingress"

          git status
          
          declare -i n
          n=0
          until [ $n -ge 5 ]
          do
            # TODO: also push to pr-$GITHUB_ACTOR branch. Can do this as a force-push at the end?
            git push origin "HEAD:pr-$GITHUB_HEAD_REF" && break
            n+=1
            git pull --rebase origin pr-$GITHUB_HEAD_REF
          done
          
          if [ $n -ge 5 ]
          then
            echo "ran out of retries"
            exit 1
          fi
